import { ConfluenceSelector } from '../confluence-selector'
import { useState } from 'react'

export default function ConfluenceSelectorExample() {
  const [selectedConfluences, setSelectedConfluences] = useState<string[]>([
    '13-ema-respect',
    'london-open',
    'railroad-tracks'
  ])
  const [notes, setNotes] = useState('Type 1 M/W Pattern setup with strong confluence:\n\n✓ 13 EMA Respect: Both legs of the M pattern respect the 13 EMA without violation\n✓ London Open: Setup formed during high volatility London session (3:30-5:30 AM EST)\n✓ Railroad Tracks: Strong reversal candlestick pattern confirmed at apex\n\nEntry triggered after apex formation with clean rejection pattern. Risk management: Stop above/below apex structure, targeting 2:1 R:R ratio.')

  return (
    <div className="max-w-2xl">
      <ConfluenceSelector
        selectedConfluences={selectedConfluences}
        onConfluenceChange={setSelectedConfluences}
        autoGeneratedNotes={notes}
        onNotesChange={setNotes}
      />
    </div>
  )
}